"""0005_sync_column_comments

Revision ID: 0005
Revises: 0004
Create Date: 2026-05-01 19:10:33.038152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment='操作用户',
               existing_nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment='操作类型: order_create/order_submit/order_cancel/param_update/stop_loss_set/take_profit_set/account_update/strategy_start/strategy_stop',
               existing_nullable=False)
    op.alter_column('audit_logs', 'resource',
               existing_type=sa.VARCHAR(length=50),
               comment='资源类型: order/strategy/account/position',
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.INTEGER(),
               comment='资源ID',
               existing_nullable=True)
    op.alter_column('audit_logs', 'detail',
               existing_type=sa.TEXT(),
               comment='操作描述',
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='变更前数据快照',
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='变更后数据快照',
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='客户端IP',
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.TEXT(),
               comment='User-Agent',
               existing_nullable=True)
    op.alter_column('audit_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='操作结果: success/failure/error',
               existing_nullable=False,
               existing_server_default=sa.text("'success'::character varying"))
    op.alter_column('audit_logs', 'error_message',
               existing_type=sa.TEXT(),
               comment='错误信息',
               existing_nullable=True)
    op.alter_column('orders', 'client_order_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='客户端幂等订单ID',
               existing_nullable=True)
    op.alter_column('users', 'totp_secret',
               existing_type=sa.VARCHAR(length=255),
               comment='加密存储的TOTP密钥',
               existing_nullable=True)
    op.alter_column('users', 'totp_enabled',
               existing_type=sa.BOOLEAN(),
               comment='是否启用2FA',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'totp_verified',
               existing_type=sa.BOOLEAN(),
               comment='2FA是否已验证（防止设置一半）',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'totp_verified',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='2FA是否已验证（防止设置一半）',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'totp_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用2FA',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'totp_secret',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='加密存储的TOTP密钥',
               existing_nullable=True)
    op.alter_column('orders', 'client_order_id',
               existing_type=sa.VARCHAR(length=64),
               comment='客户端幂等订单ID',
               existing_nullable=True)
    op.alter_column('audit_logs', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('audit_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='操作结果: success/failure/error',
               existing_nullable=False,
               existing_server_default=sa.text("'success'::character varying"))
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='User-Agent',
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='客户端IP',
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='变更后数据快照',
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='变更前数据快照',
               existing_nullable=True)
    op.alter_column('audit_logs', 'detail',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='操作描述',
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='资源ID',
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='资源类型: order/strategy/account/position',
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='操作类型: order_create/order_submit/order_cancel/param_update/stop_loss_set/take_profit_set/account_update/strategy_start/strategy_stop',
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='操作用户',
               existing_nullable=False)
    # ### end Alembic commands ###
