"""initial tables

Revision ID: d5fb4b2de1b0
Revises: 
Create Date: 2026-04-27 02:20:01.789461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fb4b2de1b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #
    # NOTE: orders <-> signals have circular FK dependency.
    # Create tables without the cross-FK first, then add it via batch.
    #
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='order_side'), nullable=False),
    sa.Column('order_type', sa.Enum('market', 'limit', 'stop_loss', 'take_profit', name='order_type'), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True, comment='Limit price'),
    sa.Column('stop_price', sa.Numeric(precision=20, scale=8), nullable=True, comment='Stop trigger price'),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False, comment='Order quantity'),
    sa.Column('filled_quantity', sa.Numeric(precision=20, scale=8), nullable=False, comment='Filled quantity'),
    sa.Column('avg_fill_price', sa.Numeric(precision=20, scale=8), nullable=True, comment='Avg fill price'),
    sa.Column('order_value', sa.Numeric(precision=20, scale=8), nullable=False, comment='Order value(USDT)'),
    sa.Column('commission', sa.Numeric(precision=20, scale=8), nullable=False, comment='Commission'),
    sa.Column('pnl', sa.Numeric(precision=20, scale=8), nullable=True, comment='Realized PnL'),
    sa.Column('status', sa.Enum('pending', 'submitted', 'partial', 'filled', 'cancelled', 'rejected', name='order_status'), nullable=False),
    sa.Column('strategy_instance_id', sa.Integer(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ),
    sa.ForeignKeyConstraint(['strategy_instance_id'], ['strategy_instances.id'], ),
    # signal_id FK added after signals table is created (circular dependency)
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_orders_account_id'), 'orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_orders_exchange_order_id'), 'orders', ['exchange_order_id'], unique=False)
    op.create_index(op.f('ix_orders_signal_id'), 'orders', ['signal_id'], unique=False)
    op.create_index(op.f('ix_orders_strategy_instance_id'), 'orders', ['strategy_instance_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_instance_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('action', sa.Enum('buy', 'sell', 'close', name='signal_action'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False, comment='置信度 0.0000 - 1.0000'),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=True, comment='建议入场价格'),
    sa.Column('stop_loss_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'expired', 'executed', 'rejected', name='signal_status'), nullable=False),
    sa.Column('executed_order_id', sa.Integer(), nullable=True),
    sa.Column('market_data', sa.JSON(), nullable=True, comment='市场数据快照'),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['executed_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['strategy_instance_id'], ['strategy_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_strategy_instance_id'), 'signals', ['strategy_instance_id'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('strategy_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('params_schema', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='strategy_risk_level'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_templates_code'), 'strategy_templates', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'banned', name='user_status'), nullable=False),
    sa.Column('risk_level', sa.Enum('conservative', 'moderate', 'aggressive', name='risk_level'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False, comment='策略模板ID'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='交易对'),
    sa.Column('exchange', sa.String(length=20), nullable=False, comment='交易所'),
    sa.Column('start_date', sa.String(length=20), nullable=False, comment='开始日期'),
    sa.Column('end_date', sa.String(length=20), nullable=False, comment='结束日期'),
    sa.Column('initial_capital', sa.Numeric(precision=20, scale=8), nullable=False, comment='初始资金'),
    sa.Column('params', sa.Text(), nullable=True, comment='策略参数 JSON'),
    sa.Column('total_return', sa.Numeric(precision=20, scale=8), nullable=False, comment='总收益'),
    sa.Column('total_return_pct', sa.Numeric(precision=10, scale=4), nullable=False, comment='总收益率%'),
    sa.Column('annual_return', sa.Numeric(precision=10, scale=4), nullable=False, comment='年化收益率%'),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=False, comment='夏普比率'),
    sa.Column('calmar_ratio', sa.Numeric(precision=10, scale=4), nullable=False, comment='卡玛比率'),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=False, comment='最大回撤%'),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='胜率%'),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=False, comment='盈亏比'),
    sa.Column('total_trades', sa.Integer(), nullable=False, comment='总交易次数'),
    sa.Column('profit_trades', sa.Integer(), nullable=False, comment='盈利次数'),
    sa.Column('loss_trades', sa.Integer(), nullable=False, comment='亏损次数'),
    sa.Column('avg_profit', sa.Numeric(precision=20, scale=8), nullable=False, comment='平均盈利'),
    sa.Column('avg_loss', sa.Numeric(precision=20, scale=8), nullable=False, comment='平均亏损'),
    sa.Column('equity_curve', sa.Text(), nullable=True, comment='权益曲线 JSON'),
    sa.Column('trades', sa.Text(), nullable=True, comment='交易记录 JSON'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='回测开始时间'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='回测结束时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_user_id'), 'backtest_results', ['user_id'], unique=False)
    op.create_table('exchange_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.Enum('binance', 'okx', 'huobi', name='exchange_name'), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False, comment='账户别名'),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False, comment='AES-256加密的API Key'),
    sa.Column('encrypted_secret_key', sa.Text(), nullable=False, comment='AES-256加密的Secret Key'),
    sa.Column('encrypted_passphrase', sa.Text(), nullable=True, comment='OKX需要AES-256加密的passphrase'),
    sa.Column('permissions', sa.String(length=50), nullable=False, comment='API权限: read,trade,withdraw'),
    sa.Column('is_demo', sa.Boolean(), nullable=False, comment='OKX模拟盘标记(x-simulated-trading)'),
    sa.Column('is_testnet', sa.Boolean(), nullable=False, comment='Binance测试网标记'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'error', 'disabled', name='account_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=20, scale=8), nullable=False, comment='可用余额(USDT)'),
    sa.Column('frozen_balance', sa.Numeric(precision=20, scale=8), nullable=False, comment='冻结余额(USDT)'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_accounts_user_id'), 'exchange_accounts', ['user_id'], unique=False)
    op.create_table('strategy_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True, comment='绑定的交易所账户，自动下单时使用'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.Enum('long', 'short', 'both', name='strategy_direction'), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('risk_params', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'running', 'paused', 'stopped', name='instance_status'), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_pnl_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['strategy_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_instances_account_id'), 'strategy_instances', ['account_id'], unique=False)
    op.create_index(op.f('ix_strategy_instances_symbol'), 'strategy_instances', ['symbol'], unique=False)
    op.create_index(op.f('ix_strategy_instances_user_id'), 'strategy_instances', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='交易对 BTC/USDT'),
    sa.Column('side', sa.Enum('long', 'short', name='position_side'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False, comment='持仓数量'),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False, comment='开仓价格'),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=False, comment='当前价格'),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=False, comment='未实现盈亏'),
    sa.Column('unrealized_pnl_percent', sa.Numeric(precision=10, scale=4), nullable=False, comment='未实现盈亏百分比'),
    sa.Column('stop_loss_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_loss_order_id', sa.String(length=100), nullable=True, comment='交易所止损条件单ID'),
    sa.Column('take_profit_order_id', sa.String(length=100), nullable=True, comment='交易所止盈条件单ID'),
    sa.Column('status', sa.Enum('open', 'closed', 'liquidated', name='position_status'), nullable=False),
    sa.Column('strategy_instance_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ),
    sa.ForeignKeyConstraint(['strategy_instance_id'], ['strategy_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_account_id'), 'positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_positions_strategy_instance_id'), 'positions', ['strategy_instance_id'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_strategy_instance_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_account_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_strategy_instances_user_id'), table_name='strategy_instances')
    op.drop_index(op.f('ix_strategy_instances_symbol'), table_name='strategy_instances')
    op.drop_index(op.f('ix_strategy_instances_account_id'), table_name='strategy_instances')
    op.drop_table('strategy_instances')
    op.drop_index(op.f('ix_exchange_accounts_user_id'), table_name='exchange_accounts')
    op.drop_table('exchange_accounts')
    op.drop_index(op.f('ix_backtest_results_user_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_strategy_templates_code'), table_name='strategy_templates')
    op.drop_table('strategy_templates')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_strategy_instance_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_strategy_instance_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_signal_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_exchange_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_account_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
