apiVersion: 1

datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "120s"
      httpMethod: "POST"
      manageAlerts: true
    version: 1

  # TimescaleDB datasource
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}
    editable: true
    jsonData:
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: true
    version: 1
